### ISSUE TITLE
Please unify the license

### ISSUE THREAD

**Issue by magnetophon** [brummer10/MelMatchEQ.lv2#1]
Thanks for another great plugin!

When I did a PR to package it into NixOS, @sikmir pointed out that there are 2 licenses in the repo:
It's gpl3 according to [LICENSE](https://github.com/brummer10/MelMatchEQ.lv2/blob/master/LICENSE), but gpl2Plus according to [sources](https://github.com/brummer10/MelMatchEQ.lv2/blob/3d91ab9eefe130986d2e6b7700c14726d85d044c/plugin/gx_melmatcheq.h#L6).

Could you please unify those?

**Comment by brummer10** [comment]
Thanks for pointing out the issue. I've updated the LICENCE file now. The hole project is meant to be under the GPL2 
 or (at your option) any later version.
And thanks for distribute my work, very appreciated.

**Comment by magnetophon** [comment]
Thank *you*!  :)
